### ISSUE TITLE
Add support for training Starcraft 1 Broodwar AIs

### ISSUE THREAD

**Issue by krasi0** [opendilab/DI-star#11]
Hey! Awesome work so far!
It would be really cool if (a fork of) the DI-star environment also had support for training Starcraft 1 Broodwar AIs using BWAPI ( https://github.com/bwapi/bwapi ).
The Broodwar AI community has been very competitive for over a decade now and the current top bots are already at or above the playing strength of average human players.
Some more references if you are interested:
https://sscaitournament.com/
https://www.basil-ladder.net/

Keep up the good work! :)

**Comment by upia99** [comment]
Thanks!
AI in SC1 have done some great work as we know, basically it is the beginning of modern game AI history, we really appreciate that.  It would be great to train AI in SC1 using this project.
We are focusing on imporving performance right now, I'm afraid we don't have that much time to do it. We'd love to help if you are planning on that.

**Comment by speaknowpotato** [comment]
IA IA IA

**Comment by krasi0** [comment]
@upia99 Thank you for your answer! :+1: 
I won't have much free time this year either, but I bet that there are other people from the SC1 BW AI community that would be interested in this project.
What are the hardware requirements for relatively fast training of a new agent?

**Comment by upia99** [comment]
One 1080TI with several days training will have a playable agent, we use 100+ V100 for decent performance
