### ISSUE TITLE
关于HVA状态下的快捷键问题

### ISSUE THREAD

**Issue by Hammerstein3217** [opendilab/DI-star#15]
Hello IA大哥，我在本地运行Windows版的DI-star并尝试与AI对抗时发现一个问题
基于这个环境下启动的星际争霸2没有办法正确读取我账号对应的自定义快捷键文件
请问这是我设置的问题吗？还是说是一个还没有实现的功能

期待回复

**Comment by upia99** [comment]
https://github.com/opendilab/DI-star/blob/main/docs/%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B.md#%E5%B0%8F%E8%B4%B4%E5%A3%AB
这里有教程哦

**Comment by Hammerstein3217** [comment]
您好，地鼠（刘航）已经收到你的邮件，正在查看
