### ISSUE TITLE
开放出来的模型是蒸馏或者剪枝的吗？感觉性能很差

### ISSUE THREAD

**Issue by hellojiaru** [opendilab/DI-star#17]
看大小都是150M左右的小模型，打了几场感觉应变很差，套路也很固定也基本没侦察。放点战术就死了，比如两矿堵口速飞龙，看到飞龙才知道补防空，而且打哪个矿补哪个，2矿骚了一波去主矿竟然都没补。看到堵口以后完全没有应对，没下三矿也没侦察，也没预判飞龙。不知道原始的大模型是否也是这样？（ps：我zvz很菜，正常打是打不过，只能放战术）

**Comment by upia99** [comment]
开源的是原始模型没有经过蒸馏，测试效果可以先看一下命令行窗口有没有频繁的warning，agent的延迟在1-2帧以内能够保证性能。AI策略相对固定，水平判断请以第一局对战为准，AI现在面对堵口战术的时候确实会有应对问题，原因在于训练整个阶段缺少这类战术的使用。
