### ISSUE TITLE
关于模型训练

### ISSUE THREAD

**Issue by pmy0721** [opendilab/DI-star#18]
您好，请问如果想用4.10.0版本的replays进行监督学习，要去哪里找更多对应版本（4.10.0）的replays呢？我已经试过在[s2client-proto](https://github.com/Blizzard/s2client-proto)通过终端命令下载了4.10.0版本的replays，但却无法用4.10.0版本的客户端进行播放（提示游戏执行所参照的模块或地图关联内容已不可用，如下图），貌似外服录像无法用国服客户端打开？
![80285d086e061d955e52342f26f40ad162d9cabe](https://user-images.githubusercontent.com/85235079/174474279-9505a511-b36b-4b59-90a4-19cf6ebf62d0.jpg)

**Comment by zxzzz0** [comment]
Did you follow the guidance here? https://github.com/opendilab/DI-star/tree/main/docs

**Comment by pmy0721** [comment]
Thank you. I will have a try.

**Comment by pmy0721** [comment]
> Did you follow the guidance here? https://github.com/opendilab/DI-star/tree/main/docs

Thank you. I will have a try.

**Comment by etbox** [comment]
I got the same problem with the same error message here. After reading docs from `docs/guidance_to_small_scale_training.md#replay-versions` and downloading all ladder maps from [s2client-proto](https://github.com/Blizzard/s2client-proto#map-packs) to `$SC2PATH/Maps`, I am still unable to download old version client by double clicking replays from `data/replays` in Windows 10 except v4.10.0 . Although both the docs and  [Customer support from Blizzard](https://us.forums.blizzard.com/en/sc2/t/any1-can-help-me-how-to-view-old-replays-again/19402) said that old version clients should be downloaded automatically, the game just pop up the error message.

And I found that there are only 2 clients in `$SC2PATH/Versions`:
![image](https://user-images.githubusercontent.com/16815152/197162242-440a9b12-c2b0-40b1-b2c1-0845cc81f6ab.png)

So could you please offer full old version clients in Windows by a download link?
