### ISSUE TITLE
关于replay数据问题

### ISSUE THREAD

**Issue by gegeguai** [opendilab/DI-star#22]
想问一下有没有最新版本的5.0.9的replay数据，或者如何去获得这些replay数据呢？

**Comment by upia99** [comment]
https://github.com/Blizzard/s2client-proto/tree/master/samples/replay-api
通过这个api能下载5.0.4以前的replay
5.0.9只有自己打的或者找一些比赛replay：https://liquipedia.net/starcraft2/Premier_Tournaments
