### ISSUE TITLE
Unable to download models

### ISSUE THREAD

**Issue by Misterion777** [opendilab/DI-star#23]
Hi, when running `python -m distar.bin.download_model --name rl_model` i am getting `Operation timed out` error. Can you please check if your servers are up?

**Comment by upia99** [comment]
Web server is out of service, we will recover it soon.
You can download models here, unzip them into distar/bin/
https://drive.google.com/file/d/18y4OuM4ObGydMBLrpzT5po0IJkavlNle/view?usp=sharing
