### ISSUE TITLE
[Feature Request] Docs Support

### ISSUE THREAD

**Issue by ain-soph** [opendilab/DI-star#27]
I'm glad to see that this repo is continuously maintained this year, and still hope to make contribution.  
But I find it's quite difficult to get started, and good docs/tutorials are in strong demand.

If you can make a short introduction for the code architecture, I can help construct a doc template (like this: [trojanzoo](https://ain-soph.github.io/trojanzoo)), so that we can together work on it.

Of course, this must be based on the assumption that the api architecture is already fixed.

**Comment by PaParaZz1** [comment]
Thank you for your interest in our project. We will be updating the training API with a new version at the end of November. Until then, if you have some spare time, we can add more detailed documentation and technical blogs together.
