### ISSUE TITLE
suggest gpu for notebook user



### ISSUE THREAD

**Issue by seetimee** [opendilab/DI-star#28]
may i know your suggestion for gpu on laptop computer?

**Comment by upia99** [comment]
what's the GPU type of your laptop?

**Comment by seetimee** [comment]
I would like to buy a new laptop for exploring Di -star and training my own agent.But since my budget is limited I have to choose the most cost-effective which most likely between 3050 to 3070.

---Original---
From: "Hang ***@***.***&gt;
Date: Mon, Nov 7, 2022 16:29 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [opendilab/DI-star] suggest gpu for notebook user=0A (Issue #28)




 
what's the GPU type of your laptop?

**Comment by upia99** [comment]
Training a decent agent requires  32G RAM、 8G GPU in our baseline. We didn't the performance with lower resources. If you just want to explore the code and pipeline of training, you can test it with cpu.

**Comment by seetimee** [comment]
thanks for your tip.(●'◡'●)

---Original---
From: "Hang ***@***.***&gt;
Date: Tue, Nov 15, 2022 09:35 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [opendilab/DI-star] suggest gpu for notebook user=0A (Issue #28)




 
Training a decent agent requires  32G RAM、 8G GPU in our baseline. We didn't the performance with lower resources. If you just want to explore the code and pipeline of training, you can test it with cpu.
