### ISSUE TITLE
how can the agent play terran or protoss 

### ISSUE THREAD

**Issue by qihouji** [opendilab/DI-star#29]
I've read the code and found terran and protoss in the encoding. Is there a way to build a agent for terran or protoss?

**Comment by upia99** [comment]
Now we only have pretrain model for zerg, you can train other races on your own.
You can change race in config at both training ([here](https://github.com/opendilab/DI-star/blob/main/distar/bin/sl_user_config.yaml#L37)) and evaluation([here)](https://github.com/opendilab/DI-star/blob/main/distar/bin/user_config.yaml#L36)

**Comment by qihouji** [comment]
Thanks for your reply. And how to train agents to play against different races with RL? Such as ZvT or ZvP agents

**Comment by upia99** [comment]
also in config [(here)](https://github.com/opendilab/DI-star/blob/main/distar/bin/rl_user_config.yaml#L168)
