### ISSUE TITLE
Doesn't run with numpy version >= 1.24

### ISSUE THREAD

**Issue by michaelnew** [opendilab/DI-star#31]
Getting this error when trying to run: `module 'numpy' has no attribute 'int'. Did you mean: 'inf'?`.

Looks like the latest version of numpy, `np.int` was removed, and it's just `int` now, or potentially `np.int32` and `np.int64`. I don't know enough about the codebase to do a PR with the updates, but a simple fix for now is to just pin the numpy version with `numpy==1.23.5` in `setup.py`.

**Comment by upia99** [comment]
thanks, I will fix this version in setup.py
