### ISSUE TITLE
Question about contributing

### ISSUE THREAD

**Issue by ain-soph** [opendilab/DI-star#32]
李培楠nb！@upia99
咱这啥时候能开发好啊🤔CN星际都要画上完美句号啦
对目前的开发进度不是很清楚。我作为external contributor能做些什么吗？

**Comment by ain-soph** [comment]
利用新的pytorch 2.0的compile功能能否为train和evaluate提速呢？可能实际游玩的时候能提升不少效果？

**Comment by PaParaZz1** [comment]
> 利用新的pytorch 2.0的compile功能能否为train和evaluate提速呢？可能实际游玩的时候能提升不少效果？

要等他具体出来之后实测下，因为DI-star的计算图其实很不规整，加速比目前只能谨慎看待
