### ISSUE TITLE
Invalid discord invite link

### ISSUE THREAD

**Issue by haha454** [opendilab/DI-star#35]
The [Discord invite](https://discord.gg/4ZDVwb97) is invalid.

![image](https://github.com/opendilab/DI-star/assets/12334692/c444a457-0a82-4f9b-b235-93ee0d4d9bf9)

**Comment by upia99** [comment]
here is the new discord link: https://discord.gg/y9urHVuH
BTW, it's not very active now, if you have any questions, ask here
