### ISSUE TITLE
Invalid Discord Link

### ISSUE THREAD

**Issue by AllisonLT** [opendilab/DI-star#36]
The link in the last update is invalid now.

I'm a new fan(SC2 newbie). Wanna learn more. -v-

**Comment by TuTuHuss** [comment]
Hi AllisonLT,

Thank you for your continued interest in our DI-star project. I appreciate your reminder that the Discord link provided in the readme document has expired. To ensure you can join us seamlessly, I'm providing the updated Discord link below. We'd be delighted to have you on board!

Link: https://discord.gg/dkZS2JF56X

**Comment by TuTuHuss** [comment]
https://github.com/opendilab/DI-star/pull/37

**Comment by TuTuHuss** [comment]
[https://github.com/opendilab/DI-star/pull/37](url)

**Comment by PaParaZz1** [comment]
We have updated the discord link in #37
