### ISSUE TITLE
Making external Google codes as dependencies (and some suggestions)

### ISSUE THREAD

**Issue by ain-soph** [opendilab/DI-star#4]
Hi!  
After checking this repo, it seems quite some codes are from [pysc2](https://github.com/deepmind/pysc2). Those codes might better serve as an installed package, rather than cloned in this repo.  

And I hope that there could be an abstract to illustrate the contribution of this repo, such as the code structures, algorithm and mechanism figures. Docs and test CI workflows are also important. Currently it's a little difficult to catch up without a clear guidance, but I'm quite willing to contribute in the future.

Btw, is IA himself the maintainer of this repo? Quite amazing.

**Comment by Wormh0-le** [comment]
In last night live streaming at scboy, yes , IA said he is the main maintainer of this repo.

**Comment by PaParaZz1** [comment]
> Hi!
> After checking this repo, it seems quite some codes are from [pysc2](https://github.com/deepmind/pysc2). Those codes might better serve as an installed package, rather than cloned in this repo.
> 
> And I hope that there could be an abstract to illustrate the contribution of this repo, such as the code structures, algorithm and mechanism figures. Docs and test CI workflows are also important. Currently it's a little difficult to catch up without a clear guidance, but I'm quite willing to contribute in the future.
> 
> Btw, is IA himself the maintainer of this repo? Quite amazing.

- For pysc2, we modify something about the original pysc2, such as [action_dict](https://github.com/opendilab/DI-star/blob/main/ctools/pysc2/lib/action_dict.py), polish the data preprocessing in [features](https://github.com/opendilab/DI-star/blob/main/ctools/pysc2/lib/features.py) and so on. Therefore, just install the original pysc2 is not enough, and we will add this message in `README.md`.
- For more parts about docs and CI workflows, we will release the whole training pipeline in August, together with these parts you mentioned. And some technical blogs are also ready to release. Our developers were busy with [DI-engine](https://github.com/opendilab/DI-engine) before, now we will pay more attention to this repo.
- IA leads the whole SC2 AI project indeed, both algorithm design and code implementation, if approved, we will release some interesting commit records. (hhh
- We welcome any developers who are willing to participate together, and you can add any issues about this project. More discussion and share are the value of open-source project.

**Comment by ain-soph** [comment]
What a great news! Look forward to the progress. I’ll see if I can get involved after the roadmap and to-do issues get released.

**Comment by speaknowpotato** [comment]
hi @PaParaZz1 , happy new year!
do we have any update on the whole training pipeline or the docs that we can follow?
thanks in advance!

**Comment by PaParaZz1** [comment]
Hello, We are going to update the whole training pipeline of DI-star by the end of January 2022.

2022-01-09 02:10:54Speaknow ***@***.***>wrote:

hi @PaParaZz1 , happy new year!
do we have any update on the whole training pipeline or the docs that we can follow?
thanks in advance!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PaParaZz1** [comment]
And you can join our slack channel for more details (https://join.slack.com/t/opendilab/shared_invite/zt-v9tmv4fp-nUBAQEH1_Kuyu_q4plBssQ)

-----Original Messages-----
From:Speaknow ***@***.***>
Sent Time:2022-01-09 02:10:54 (Sunday)
To: opendilab/DI-star ***@***.***>
Cc: Swain ***@***.***>, Mention ***@***.***>
Subject: Re: [opendilab/DI-star] Making external Google codes as dependencies (and some suggestions) (#4)






hi @PaParaZz1 , happy new year!
do we have any update on the whole training pipeline or the docs that we can follow?
thanks in advance!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
