### ISSUE TITLE
Error when running python -m distar.bin.play

### ISSUE THREAD

**Issue by rightly0716** [opendilab/DI-star#8]
I got an error when initializing the ai:

ImportError: cannot import name 'container_abcs' from 'torch._six' (C:\ProgramData\Miniconda3\lib\site-packages\torch\_six.py)

Pytorch Version (Cuda v11)

torch                         1.9.0
torchaudio                    0.9.0
torchvision                   0.10.0

Did some search and think this is relevant to torch version. What is the version that dev is using? Thanks!

**Comment by PaParaZz1** [comment]
please refer to `README.md`—— `Pytorch Version 1.7.1 and CUDA is recommended`. Your problem maybe have relationship with the upgrade after torch1.8.0.

**Comment by rightly0716** [comment]
Got it. Thanks!

**Comment by ain-soph** [comment]
@rightly0716  See #7 for the potential fix.  
Pytorch abandons `torch._six.container_abcs` after 1.9.0.

**Comment by rightly0716** [comment]
Yes, the solution works! Thanks a lot!
